### ISSUE TITLE
Create tests for dinamizators

### ISSUE THREAD

**Issue by renan-eccel** [renan-eccel/instances-DDARP-DPDPTW#1]
We need tests!

**Comment by KaramiF** [comment]
I have a problem while I am running test_poisson.py  and the following issue while I am running test_analysis_tools.py

 hdf = analysis_tools.calculate_dynamism(df)
TypeError: calculate_dynamism() missing 2 required positional arguments: 'columns_to_group' and 'perfect_interarrival_parameter'

Would be possible for you to resolve the issue?
